[package]
name = "bridge-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["abigen", "ws"] }
tokio = { version = "1.36", features = ["full"] }
dotenv = "0.15"
